// Generated by gencpp from file tca_turtlebot/MoveBaseInterfaceAction.msg
// DO NOT EDIT!


#ifndef TCA_TURTLEBOT_MESSAGE_MOVEBASEINTERFACEACTION_H
#define TCA_TURTLEBOT_MESSAGE_MOVEBASEINTERFACEACTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <tca_turtlebot/MoveBaseInterfaceActionGoal.h>
#include <tca_turtlebot/MoveBaseInterfaceActionResult.h>
#include <tca_turtlebot/MoveBaseInterfaceActionFeedback.h>

namespace tca_turtlebot
{
template <class ContainerAllocator>
struct MoveBaseInterfaceAction_
{
  typedef MoveBaseInterfaceAction_<ContainerAllocator> Type;

  MoveBaseInterfaceAction_()
    : action_goal()
    , action_result()
    , action_feedback()  {
    }
  MoveBaseInterfaceAction_(const ContainerAllocator& _alloc)
    : action_goal(_alloc)
    , action_result(_alloc)
    , action_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::tca_turtlebot::MoveBaseInterfaceActionGoal_<ContainerAllocator>  _action_goal_type;
  _action_goal_type action_goal;

   typedef  ::tca_turtlebot::MoveBaseInterfaceActionResult_<ContainerAllocator>  _action_result_type;
  _action_result_type action_result;

   typedef  ::tca_turtlebot::MoveBaseInterfaceActionFeedback_<ContainerAllocator>  _action_feedback_type;
  _action_feedback_type action_feedback;





  typedef boost::shared_ptr< ::tca_turtlebot::MoveBaseInterfaceAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tca_turtlebot::MoveBaseInterfaceAction_<ContainerAllocator> const> ConstPtr;

}; // struct MoveBaseInterfaceAction_

typedef ::tca_turtlebot::MoveBaseInterfaceAction_<std::allocator<void> > MoveBaseInterfaceAction;

typedef boost::shared_ptr< ::tca_turtlebot::MoveBaseInterfaceAction > MoveBaseInterfaceActionPtr;
typedef boost::shared_ptr< ::tca_turtlebot::MoveBaseInterfaceAction const> MoveBaseInterfaceActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tca_turtlebot::MoveBaseInterfaceAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tca_turtlebot::MoveBaseInterfaceAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tca_turtlebot::MoveBaseInterfaceAction_<ContainerAllocator1> & lhs, const ::tca_turtlebot::MoveBaseInterfaceAction_<ContainerAllocator2> & rhs)
{
  return lhs.action_goal == rhs.action_goal &&
    lhs.action_result == rhs.action_result &&
    lhs.action_feedback == rhs.action_feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tca_turtlebot::MoveBaseInterfaceAction_<ContainerAllocator1> & lhs, const ::tca_turtlebot::MoveBaseInterfaceAction_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tca_turtlebot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tca_turtlebot::MoveBaseInterfaceAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tca_turtlebot::MoveBaseInterfaceAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tca_turtlebot::MoveBaseInterfaceAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tca_turtlebot::MoveBaseInterfaceAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tca_turtlebot::MoveBaseInterfaceAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tca_turtlebot::MoveBaseInterfaceAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tca_turtlebot::MoveBaseInterfaceAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "03c2f5f0caa468814f87a8edd9f7bd87";
  }

  static const char* value(const ::tca_turtlebot::MoveBaseInterfaceAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x03c2f5f0caa46881ULL;
  static const uint64_t static_value2 = 0x4f87a8edd9f7bd87ULL;
};

template<class ContainerAllocator>
struct DataType< ::tca_turtlebot::MoveBaseInterfaceAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tca_turtlebot/MoveBaseInterfaceAction";
  }

  static const char* value(const ::tca_turtlebot::MoveBaseInterfaceAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tca_turtlebot::MoveBaseInterfaceAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"MoveBaseInterfaceActionGoal action_goal\n"
"MoveBaseInterfaceActionResult action_result\n"
"MoveBaseInterfaceActionFeedback action_feedback\n"
"\n"
"================================================================================\n"
"MSG: tca_turtlebot/MoveBaseInterfaceActionGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"MoveBaseInterfaceGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: tca_turtlebot/MoveBaseInterfaceGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Goal\n"
"geometry_msgs/PoseStamped wpt\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: tca_turtlebot/MoveBaseInterfaceActionResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"MoveBaseInterfaceResult result\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalStatus\n"
"GoalID goal_id\n"
"uint8 status\n"
"uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n"
"uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n"
"uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n"
"                            #   and has since completed its execution (Terminal State)\n"
"uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n"
"uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n"
"                            #    to some failure (Terminal State)\n"
"uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n"
"                            #    because the goal was unattainable or invalid (Terminal State)\n"
"uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n"
"                            #    and has not yet completed execution\n"
"uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n"
"                            #    but the action server has not yet confirmed that the goal is canceled\n"
"uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n"
"                            #    and was successfully cancelled (Terminal State)\n"
"uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n"
"                            #    sent over the wire by an action server\n"
"\n"
"#Allow for the user to associate a string with GoalStatus for debugging\n"
"string text\n"
"\n"
"\n"
"================================================================================\n"
"MSG: tca_turtlebot/MoveBaseInterfaceResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Result \n"
"bool res\n"
"\n"
"================================================================================\n"
"MSG: tca_turtlebot/MoveBaseInterfaceActionFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"MoveBaseInterfaceFeedback feedback\n"
"\n"
"================================================================================\n"
"MSG: tca_turtlebot/MoveBaseInterfaceFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Progress\n"
"float32 progress\n"
;
  }

  static const char* value(const ::tca_turtlebot::MoveBaseInterfaceAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tca_turtlebot::MoveBaseInterfaceAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_goal);
      stream.next(m.action_result);
      stream.next(m.action_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveBaseInterfaceAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tca_turtlebot::MoveBaseInterfaceAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tca_turtlebot::MoveBaseInterfaceAction_<ContainerAllocator>& v)
  {
    s << indent << "action_goal: ";
    s << std::endl;
    Printer< ::tca_turtlebot::MoveBaseInterfaceActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    s << indent << "action_result: ";
    s << std::endl;
    Printer< ::tca_turtlebot::MoveBaseInterfaceActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    s << indent << "action_feedback: ";
    s << std::endl;
    Printer< ::tca_turtlebot::MoveBaseInterfaceActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TCA_TURTLEBOT_MESSAGE_MOVEBASEINTERFACEACTION_H
