// Generated by gencpp from file tca_turtlebot/GwptService.msg
// DO NOT EDIT!


#ifndef TCA_TURTLEBOT_MESSAGE_GWPTSERVICE_H
#define TCA_TURTLEBOT_MESSAGE_GWPTSERVICE_H

#include <ros/service_traits.h>


#include <tca_turtlebot/GwptServiceRequest.h>
#include <tca_turtlebot/GwptServiceResponse.h>


namespace tca_turtlebot
{

struct GwptService
{

typedef GwptServiceRequest Request;
typedef GwptServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GwptService
} // namespace tca_turtlebot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tca_turtlebot::GwptService > {
  static const char* value()
  {
    return "78ad5397dff8517113a4ce521add09a7";
  }

  static const char* value(const ::tca_turtlebot::GwptService&) { return value(); }
};

template<>
struct DataType< ::tca_turtlebot::GwptService > {
  static const char* value()
  {
    return "tca_turtlebot/GwptService";
  }

  static const char* value(const ::tca_turtlebot::GwptService&) { return value(); }
};


// service_traits::MD5Sum< ::tca_turtlebot::GwptServiceRequest> should match
// service_traits::MD5Sum< ::tca_turtlebot::GwptService >
template<>
struct MD5Sum< ::tca_turtlebot::GwptServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tca_turtlebot::GwptService >::value();
  }
  static const char* value(const ::tca_turtlebot::GwptServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tca_turtlebot::GwptServiceRequest> should match
// service_traits::DataType< ::tca_turtlebot::GwptService >
template<>
struct DataType< ::tca_turtlebot::GwptServiceRequest>
{
  static const char* value()
  {
    return DataType< ::tca_turtlebot::GwptService >::value();
  }
  static const char* value(const ::tca_turtlebot::GwptServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tca_turtlebot::GwptServiceResponse> should match
// service_traits::MD5Sum< ::tca_turtlebot::GwptService >
template<>
struct MD5Sum< ::tca_turtlebot::GwptServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tca_turtlebot::GwptService >::value();
  }
  static const char* value(const ::tca_turtlebot::GwptServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tca_turtlebot::GwptServiceResponse> should match
// service_traits::DataType< ::tca_turtlebot::GwptService >
template<>
struct DataType< ::tca_turtlebot::GwptServiceResponse>
{
  static const char* value()
  {
    return DataType< ::tca_turtlebot::GwptService >::value();
  }
  static const char* value(const ::tca_turtlebot::GwptServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TCA_TURTLEBOT_MESSAGE_GWPTSERVICE_H
